# Configure Netlify builds.
[build]
  publish = "dist/"
  command = "yarn astro dev"

# Request bots not to index the admin section.
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex"