backend:
  # name: test-repo
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

# Uncomment local_backend when you need to develop in your local
# local_backend: true # run npx netlify-cms-proxy-server for local testing
logo_url: ../assets/logo.svg
media_folder: "static/assets"
public_folder: "/assets"

collections:

  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    editor:
      preview: false
    label: "Posts" # Used in the UI
    label_singular: "Post" # Used in the UI, ie: "New Post"
    description: >
      Create awesome stuff here.
    folder: "src/content/posts"
    slug: "{{slug}}"
    summary: "{{title}} — {{year}}/{{month}}/{{day}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Template",
          name: "template",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    editor:
      preview: false
    label: "Posts" # Used in the UI
    label_singular: "Post" # Used in the UI, ie: "New Post"
    description: >
      Create awesome stuff here.
    folder: "src/content/posts"
    slug: "{{slug}}"
    summary: "{{title}} — {{year}}/{{month}}/{{day}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Template",
          name: "template",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }