
				backend: {
					name: 'git-gateway',
					branch: 'main',
				},
				// Configure where our media assets are stored & served from
				media_folder: 'src/content/post/',
				public_folder: '',
				// Configure the content collections
				collections: [
					{
						folder: "src/content/post",
						name: 'posts',
						label: 'Blog Posts',
						label_singular: 'Blog Post',
						path: '{{slug}}/index',
						media_folder: '',
						public_folder: '/{{media_folder}}',
						create: true,
						delete: true,
						fields: [
							{ name: 'title', widget: 'string', label: 'Post Title' },
							{
								label: "Featured Image",
								name: "featuredImage",
								widget: "image",
								hint: "The primary image used for all social media, blog previews and the feature image at the top of the post",
								required: false,
							},
							{
								name: 'publishDate',
								widget: 'datetime',
								format: 'DD MMM YYYY',
								date_format: 'DD MMM YYYY',
								time_format: false,
								label: 'Publish Date',
							},
							{ name: 'author', widget: 'string', label: 'Author Name', required: false },
							{ name: 'authorURL', widget: 'string', label: 'Author URL', required: false },
							{ name: 'description', widget: 'string', label: 'Description', required: false },
							{ name: 'body', widget: 'markdown', label: 'Post Body' },
							{
								name: 'layout',
								widget: 'select',
								default: '../../layouts/BlogPost.astro',
								required: false,
								options: [
									{ label: 'Blog Post', value: '../../layouts/BlogPost.astro', },
								],
							},
						],
					},
				],
